// Answers that aren't in any list but deserve a smile instead of a plain "no".
import { keyOf } from "./match.js";

const QUIPS = {
  idk: "The monster waits patiently. It doesn't know either.",
  dunno: "The monster waits patiently. It doesn't know either.",
  pass: "There's no passing here, only answering.",
  skip: "Doors don't open for skippers.",
  nothing: "Nothing is not on the list. Sadly.",
  help: "Pip would help, but Pip is a chest.",
  yes: "Yes what? The monster tilts its head.",
  no: "The monster looks a little hurt.",
  hi: "Hello! Now, the question…",
  hello: "Hello! Now, the question…",
  wakanda: "Wakanda is fictional. The mouse checked a map.",
  narnia: "Narnia is through a wardrobe, not down here.",
  atlantis: "Atlantis sank. So did that answer.",
  mordor: "One does not simply walk into this list.",
  hogwarts: "Wrong castle.",
  gotham: "Gotham is fictional, however gloomy.",
  eldorado: "El Dorado was never found. Neither was that answer.",
  neverland: "Second star to the right, but not in this room.",
  middleearth: "Tolkien would be flattered. The monster isn't.",
  asgard: "Asgard is a realm, not the answer.",
  tatooine: "A long time ago, in a different list.",
  westeros: "Winter came, the answer didn't.",
  ophiuchus: "The 13th sign? Astronomers say yes, horoscopes say no.",
  liger: "Napoleon Dynamite's favourite, but not a wild species.",
  unicorn: "Scotland's national animal, but not real enough for this list.",
  greenland: "Greenland belongs to the Kingdom of Denmark.",
  puertorico: "Puerto Rico is a US territory, not a country or a state.",
  hongkong: "Hong Kong is a special region of China.",
  antarctica: "Antarctica is a continent without a country.",
  europe: "That's a whole continent!",
  africa: "That's a whole continent!",
  asia: "That's a whole continent!",
  america: "Which part?",
  pokemon: "Gotta name 'em somewhere else.",
  potato: "Always a strong answer. Just not here.",
  banana: "Bananas are everywhere, but not in this room.",
  cheese: "Cheese makes everything better, but not this.",
  pip: "Pip blushes.",
  pocketquest: "Flattery won't open this door.",
  dragon: "Hush, she might hear you.",
  oldember: "She's asleep. Don't wake her.",
  sun: "It's a star, and not the one you need.",
  moon: "Lovely tonight, but not the answer.",
  god: "Which one?",
  me: "You're lovely, but not on the list.",
  you: "The monster points at itself, confused.",
};

export function quipFor(text) {
  return QUIPS[keyOf(text)] || null;
}
